# Generated by Django 5.0.7 on 2024-07-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nombre_obra_obra_direccion_obra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='Nombre_tarea',
            new_name='nombre_tarea',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='unidad_media',
            field=models.CharField(choices=[('ml', 'Metros Lineales'), ('m2', 'Metros Cuadrados')], max_length=2),
        ),
    ]
