# Generated by Django 5.0.7 on 2024-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tarea_codigo_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='codigo_tarea',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
